<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Metalsmith Test Site</title>

        <meta name="viewport" content="width=device-width">

        <link href="/styles/main.css" rel="stylesheet" type="text/css" />
    </head>
    <body>

        <header>
            <h1 class="logo"><a href="/">Metalsmith Test Site</a></h1>
        </header>


        <div class="main-wrapper">

